### ISSUE TITLE
[Code UW]: Create CONTRIBUTING.md file

### ISSUE THREAD

**Issue by carlosgjs** [uw-ssec/codeuw#10]
### Contact

carlosg@uw.edu

### Description

The noisepy README currently has guidelines for contributing to the project. The preferred way of doing this is to split them into a separate CONTRIBUTING.md file at the root. 

### Code Repository

https://github.com/mdenolle/NoisePy

### Version

L1

### What is the primary programming language for the task

Other (specify in the description)

**Comment by nrich20** [comment]
CONTRIBUTING.md file created.

**Comment by nrich20** [comment]
@carlosgjs This task has been completed and approved
