### ISSUE TITLE
[Code UW]: Rename noisepy testing directories

### ISSUE THREAD

**Issue by carlosgjs** [uw-ssec/codeuw#11]
### Contact

carlosg@uw.edu

### Description

For legacy reasons, the `tests` directory contains one-of manual testing scripts, while the `unittests` directory has actual pytest tests. This task consists of:

1) Renaming (via `git mv`):
`test` --> `scripts`
`unittests` --> `tests`

2) Update the [unit test job](https://github.com/mdenolle/NoisePy/blob/0028f03c11948e1a4933390c611205e6231fec05/.github/workflows/test.yaml#L21) to run tests in the renamed `tests` directory.

### Code Repository

https://github.com/mdenolle/NoisePy

### Task level

L1

### What is the primary programming language for the task

shell

**Comment by nrich20** [comment]
Folders renamed and test file updated to reflect the renaming.

**Comment by nrich20** [comment]
@carlosgjs This task has been completed and approved
