### ISSUE TITLE
[Code UW]: Implement a Zarr CrossCorrelationDataStore

### ISSUE THREAD

**Issue by carlosgjs** [uw-ssec/codeuw#13]
### Contact

carlosg@uw.edu

### Description

The NoisePy package computes cross-correlations of seismic signals and writes them out using the `CrossCorrelationDataStore` abstraction. Currently the only implementation is the `ASDFCCStore`, which as its name implies writes to ASDF files. 

We would like the ability to write to [Zarr](https://zarr.readthedocs.io/en/stable/) files as this will provide a more efficient reading mechanism for downstream tasks.

### Code Repository

https://github.com/mdenolle/NoisePy

### Task level

L3

### What is the primary programming language for the task

python

**Comment by lsetiawan** [comment]
I think this is done in https://github.com/mdenolle/NoisePy/pull/150
