### ISSUE TITLE
[Code UW]: NoisePy - Change config values to be enums

### ISSUE THREAD

**Issue by carlosgjs** [uw-ssec/codeuw#20]
### Contact

carlosg@uw.edu

### Description

The `ConfigParameters` fields `freq_norm`, `time_norm`, `cc_method` and `rm_resp`,  in `src/noisepy/seis/datetypes.py`,  are currently of type string. However, these can only take a fixed set of values, so they should enums instead.

The task is to change this for each field to an enum. E.g. for `freq_norm`:

- Create an enumeration FreqNorm with the following fields (`rma, no, phase_only`)
- Change the type of the `ConfigParameters.freq_norm` argument.
- Update these uses of `freq_norm` to in `noise_module.py`, `stack.py`, `correlate.py` to compare against the enum values instead of the string constants.
- Update the `get_started.ipynb` and `noisepy_scedc_tutorial.ipynb` notebooks in the tutorial folder to use the enum values for the `config` object.

A good example to follow that is already an enum is `stack_method`: https://github.com/noisepy/NoisePy/blob/5334d63a9ec0f7183b20e513e03d49c21cf981d6/src/noisepy/seis/datatypes.py#L191C12-L191C12

### Code Repository

https://github.com/mdenolle/NoisePy

### Task level

L2

### What is the primary programming language for the task

python

**Comment by carlosgjs** [comment]
@anujsinha3 is working on this

**Comment by anujsinha3** [comment]
@carlosgjs - Do we need to change the enum value for time_norm from "no" to "none" or is it tracked on a separate issue?

If yes to the change, do we expect any breaking change impact due to this?
