### ISSUE TITLE
[Code UW]: Offshore Geodesy - Add testing for the `time.py` utility module

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/codeuw#29]
### Contact

landungs@uw.edu

## Overview
As seen in codecov website: https://app.codecov.io/gh/uw-ssec/offshore-geodesy/blob/main/src/gnatss/utilities/time.py

Currently, the `time` utility module for the `gnatss` package has no test whatsoever. A test need to be implemented so that we know it works.

## TODO
- [x] Add new test python file at https://github.com/uw-ssec/offshore-geodesy/tree/main/tests/utilities
- [x] Add test function that import the `time` module and utilizes it

### Code Repository

https://github.com/uw-ssec/offshore-geodesy

### Task level

L1

### What is the primary programming language for the task

python

**Comment by madhavmk** [comment]
PR [uw-ssec/offshore-geodesy/pull/109](https://github.com/uw-ssec/offshore-geodesy/pull/109) has addressed this issue. I think we can close.
