### ISSUE TITLE
[Code UW]: Neglected-Diagnostics - Error on clicking 'Add filters' checkbox before submitting a search query

### ISSUE THREAD

**Issue by aniketfadia96** [uw-ssec/codeuw#30]
### Contact

aniketf@uw.edu

### Description

When a user clicks `Add filters` checkbox without submitting a search query, the web app crashes. Please refer to the below screenshot -

![image](https://github.com/uw-ssec/codeuw/assets/25303819/e04028c8-fa97-4e97-b89b-603e64ea8ace)

Expected - This error should be handled properly and when the user clicks `Add filters` checkbox without submitting a search query, the web app should not crash. If you want, you can print a message which says `Please perform a search before applying additional filters`

### Code Repository

https://github.com/uw-ssec/neglected-diagnostics

### Issue link

https://github.com/uw-ssec/neglected-diagnostics/issues/23

### Task level

L1

### What is the primary programming language for the task

python

**Comment by Jinay01** [comment]
I was trying to work on this issue but I guess the issue no longer persists. I followed all the steps shown in the repo and this issue.

Attaching a screenshot below

<img width="813" alt="Screenshot 2024-01-07 at 5 04 25 PM" src="https://github.com/uw-ssec/codeuw/assets/65496946/a35e110d-12f2-4ddc-a12a-d3a90e08aade">

Kindly look into this

**Comment by carlosgjs** [comment]
hi @Jinay01 - Yes, looks like this has been fixed since the issue was logged back in August. Thanks for looking into it.
