### ISSUE TITLE
[Code UW]: Add Citation file (CITATION.cff) for noisepy 

### ISSUE THREAD

**Issue by lsetiawan** [uw-ssec/codeuw#4]
### Contact

landungs@uw.edu

### Description

I've written about this issue in https://github.com/mdenolle/NoisePy/issues/71. There needs to be a citation file for this code so that citation isn't manually in the README and we can get different citation formats.

### Code Repository

https://github.com/mdenolle/NoisePy

### Issue link

https://github.com/mdenolle/NoisePy/issues/71

### Version

L1

### What is the primary programming language for the task

Other (specify in the description)

**Comment by nrich20** [comment]
Cff has been created and filled with all the citation information I could get from the read me. @lsetiawan Should I completely remove the citation section from the README or replace it with a note to check out the cff file?

**Comment by lsetiawan** [comment]
I think you can probably just remove it since that shows up on the right hand side of the repository.

**Comment by nrich20** [comment]
@lsetiawan the cff file has been created and merged into the main repository so I think this task has been completed.

**Comment by lsetiawan** [comment]
Very cool! I can confirm that I can get the following citation formats:

### APA

```
Jiang, C., & Denolle , M. NoisePy: a new high-performance python tool for seismic ambient noise seismology. [Computer software]. https://github.com/mdenolle/NoisePy.git
```

### BibTex

```
@software{Jiang_NoisePy_a_new,
author = {Jiang, Chengxin and Denolle , Marine},
title = {{NoisePy: a new high-performance python tool for seismic ambient noise seismology.}},
url = {https://github.com/mdenolle/NoisePy.git}
}
```

Thanks @nrich20 for working on this!!
